name: cuckoo_booru
description: A Dart-based console application for managing fanart collections from Danbooru and similar booru-style imageboards.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  args: ^2.4.2
  path: ^1.8.3
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  dio: ^5.4.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
