name: iOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
    
    - name: Build iOS IPA for AltStore
      run: |
        flutter build ios --release --no-codesign
        mkdir -p build/ios/ipa
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../ipa/Runner.ipa Payload/
    
    - name: Run iOS tests
      run: flutter test
    
    - name: Upload IPA for AltStore
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: cuckoo-booru-altstore
        path: build/ios/ipa/*.ipa
        retention-days: 30